# Class name.
class: alacritty
instance: Alacritty
general: Alacritty

# Scroll history.
history: 10000

# Scroll speed.
multiplier: 5

# Fonts
font:
  normal:
    family: monospace
    style: Regular

  bold:
    family: monospace
    style: Bold

  italic:
    family: monospace
    style: Italic

  bold_italic:
    family: monospace
    style: Bold Italic

  # Font size
  size: 10
  offset:
    y: 2

schemes:
  gruvbox: &gruvbox
    primary:
      background: "0x32302f"
      foreground: "0xebdbb2"
    normal:
      black: "0x32302f"
      red: "0xcc241d"
      green: "0x98971a"
      yellow: "0xd79921"
      blue: "0x458588"
      magenta: "0xb16286"
      cyan: "0x689d6a"
      white: "0xa89984"
    bright:
      black: "0x928374"
      red: "0xfb4934"
      green: "0xb8bb26"
      yellow: "0xfabd2f"
      blue: "0x83a598"
      magenta: "0xd3869b"
      cyan: "0x8ec97c"
      white: "0xebdbb2"

# Apply the color scheme.
colors: *gruvbox

# Background opacity
background_opacity: 0.9

# Launcher.
launcher:
  program: xdg-open
  args: []
